// v1.6.0 file:// fallback data. HTTP/GitHub Pages는 data/character_manifest.json의 assets/characters/*/character.json을 우선 사용한다.
window.HOUHOU_CHARACTER_MANIFEST = [
  "data/characters/normal_man.json",
  "data/characters/meongdungi.json",
  "data/characters/gomangi.json",
  "data/characters/eungae.json",
  "data/characters/awakened_normal_man.json",
  "data/characters/bokjujok.json",
  "data/characters/jjabbeorin.json",
  "data/characters/storm_spirit.json",
  "data/characters/vampire_king.json",
  "data/characters/fire_spirit.json",
  "data/characters/lightning_spirit.json",
  "data/characters/little_spirit.json",
  "data/characters/slimecute.json"
];
window.HOUHOU_CHARACTER_DATA = [
  {
    "id": 5,
    "key": "awakened_normal_man",
    "name": "각성한 걍사람",
    "grade": "SPECIAL",
    "hp": 200,
    "atk": 35,
    "def": 80,
    "attackSpeed": 2.5,
    "attackArea": 70,
    "attackRange": 4,
    "moveSpeed": 3,
    "bodyRadius": 56,
    "stopGap": 18,
    "critRate": 0.15,
    "attackType": "melee",
    "frameSize": 96,
    "spritePath": "assets/characters/awakened_normal_man/",
    "effectPath": "assets/effects/awakened_normal_man/attack.png",
    "effectFrames": 5,
    "gachaRate": 10,
    "attackMethod": "몸 중심에서 각성 에너지를 예열한 뒤 전방으로 방출한다. Frame1~3은 예열, Frame4부터 히트가 시작되고 Frame5는 상대 방향으로 크게 뻗는다.",
    "feature": "중심 각성 이펙트 후 전방 방출",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 4,
      "hit": 1,
      "dead": 2,
      "win": 4
    },
    "soundPath": "assets/sounds/awakened_normal_man/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 3,
    "gridAttackRange": 4,
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "x2_v0.6.1_v0.8.22_awakened_effect5_forward",
    "effectStartFrame": 0,
    "effectFrameWidth": 192,
    "centerEffect": true,
    "effectAnchor": "attacker_center",
    "effectFrameSequence": [
      0,
      1,
      2,
      3,
      4
    ],
    "effectFrameOffsets": [
      0,
      20,
      40,
      40,
      96
    ],
    "effectScale": 1.35,
    "hitEffect": true,
    "hitEffectStart": 0.6,
    "critDamageMin": 1.5,
    "critDamageMax": 3
  },
  {
    "id": 6,
    "key": "bokjujok",
    "name": "폭주족",
    "grade": "EPIC",
    "hp": 120,
    "atk": 25,
    "def": 40,
    "attackSpeed": 4,
    "attackArea": 45,
    "attackRange": 2,
    "moveSpeed": 3.5,
    "bodyRadius": 48,
    "stopGap": 16,
    "critRate": 0.15,
    "attackType": "melee",
    "frameSize": 96,
    "spritePath": "assets/characters/bokjujok/",
    "effectPath": "assets/effects/bokjujok/attack.png",
    "effectFrames": 6,
    "gachaRate": 10,
    "attackMethod": "손이 여러 개 보이도록 공격",
    "feature": "연속 손 공격",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "aiType": "rush",
    "soundPath": "assets/sounds/bokjujok/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 3.5,
    "gridAttackRange": 2,
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2
  },
  {
    "id": 4,
    "key": "eungae",
    "name": "응애",
    "grade": "NORMAL",
    "hp": 140,
    "atk": 20,
    "def": 10,
    "attackSpeed": 2,
    "attackArea": 60,
    "attackRange": 6,
    "moveSpeed": 2,
    "bodyRadius": 36,
    "stopGap": 16,
    "critRate": 0.15,
    "attackType": "projectile",
    "projectilePath": "assets/projectiles/eungae/candy.png",
    "projectileSpeed": 620,
    "frameSize": 96,
    "spritePath": "assets/characters/eungae/",
    "effectPath": "assets/effects/eungae/attack.png",
    "effectFrames": 5,
    "gachaRate": 10,
    "attackMethod": "입에서 사탕을 뱉음",
    "feature": "사탕 투사체",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "soundPath": "assets/sounds/eungae/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 2,
    "gridAttackRange": 6,
    "gridBattleRule": "30_columns_full_engine",
    "projectileSpeedCells": 8,
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "projectileFrames": 1,
    "projectileStartFrame": 0,
    "projectileFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2
  },
  {
    "id": 10,
    "key": "fire_spirit",
    "name": "불꽃정령",
    "grade": "LEGENDARY",
    "hp": 120,
    "atk": 30,
    "def": 60,
    "attackSpeed": 2,
    "attackArea": 5,
    "attackRange": 10,
    "gridAttackRange": 10,
    "moveSpeed": 2,
    "gridMoveSpeed": 2,
    "bodyRadius": 56,
    "stopGap": 18,
    "critRate": 0.15,
    "attackType": "projectile",
    "projectilePath": "assets/projectiles/fire_spirit/fire_ground.png",
    "projectileSpeedCells": 8,
    "projectileFrames": 5,
    "frameSize": 96,
    "spritePath": "assets/characters/fire_spirit/",
    "effectPath": "assets/effects/fire_spirit/attack.png",
    "effectFrames": 5,
    "soundPath": "assets/sounds/fire_spirit/",
    "gachaRate": 10,
    "attackMethod": "불꽃을 손으로 쏴서 지면을 불태운다.",
    "feature": "지면 불꽃 공격",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2,
      "win": 4
    },
    "aiType": "projectile",
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "none_fire_spirit_v0.6.5",
    "effectStartFrame": 1,
    "effectFrameWidth": 96,
    "projectileStartFrame": 1,
    "projectileFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2.5
  },
  {
    "id": 3,
    "key": "gomangi",
    "name": "고망이",
    "grade": "RARE",
    "hp": 180,
    "atk": 20,
    "def": 50,
    "damageReduction": 0.1,
    "attackSpeed": 1,
    "attackArea": 45,
    "attackRange": 2,
    "moveSpeed": 2,
    "bodyRadius": 64,
    "stopGap": 16,
    "critRate": 0.15,
    "attackType": "melee",
    "frameSize": 96,
    "spritePath": "assets/characters/gomangi/",
    "effectPath": "assets/effects/gomangi/attack.png",
    "effectFrames": 5,
    "gachaRate": 10,
    "attackMethod": "주먹을 위에서 아래로 내려친다",
    "feature": "피해 10% 감소",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "soundPath": "assets/sounds/gomangi/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 2,
    "gridAttackRange": 2,
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2
  },
  {
    "id": 7,
    "key": "jjabbeorin",
    "name": "짭버린",
    "grade": "EPIC",
    "hp": 120,
    "atk": 25,
    "def": 50,
    "attackSpeed": 4,
    "attackArea": 45,
    "attackRange": 2,
    "moveSpeed": 3.5,
    "bodyRadius": 48,
    "stopGap": 16,
    "critRate": 0.15,
    "attackType": "melee",
    "frameSize": 96,
    "spritePath": "assets/characters/jjabbeorin/",
    "effectPath": "assets/effects/jjabbeorin/attack.png",
    "effectFrames": 6,
    "gachaRate": 10,
    "attackMethod": "손등에 튀어나온 칼날손톱으로 공격",
    "feature": "칼날손톱 공격",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "aiType": "rush",
    "soundPath": "assets/sounds/jjabbeorin/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 3.5,
    "gridAttackRange": 2,
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2
  },
  {
    "id": 11,
    "key": "lightning_spirit",
    "name": "번개정령",
    "grade": "LEGENDARY",
    "hp": 120,
    "atk": 35,
    "def": 60,
    "attackSpeed": 2,
    "attackArea": 8,
    "attackRange": 10,
    "gridAttackRange": 10,
    "moveSpeed": 2,
    "gridMoveSpeed": 2,
    "bodyRadius": 56,
    "stopGap": 18,
    "critRate": 0.15,
    "attackType": "projectile",
    "projectilePath": "assets/projectiles/lightning_spirit/lightning_bolt.png",
    "projectileSpeedCells": 10,
    "projectileFrames": 4,
    "frameSize": 96,
    "spritePath": "assets/characters/lightning_spirit/",
    "effectPath": "assets/effects/lightning_spirit/attack.png",
    "effectFrames": 4,
    "soundPath": "assets/sounds/lightning_spirit/",
    "gachaRate": 10,
    "attackMethod": "번개를 손으로 쏴서 꿰뚫는다",
    "feature": "원거리 번개 공격",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2,
      "win": 4
    },
    "aiType": "projectile",
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "none_lightning_spirit_v0.8.5",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "projectileStartFrame": 0,
    "projectileFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2.5
  },
  {
    "id": 12,
    "key": "little_spirit",
    "name": "꼬마정령",
    "grade": "LEGENDARY",
    "hp": 100,
    "atk": 40,
    "def": 50,
    "attackSpeed": 2,
    "attackArea": 5,
    "attackRange": 5,
    "gridAttackRange": 5,
    "moveSpeed": 4,
    "gridMoveSpeed": 4,
    "bodyRadius": 36,
    "stopGap": 14,
    "critRate": 0.15,
    "attackType": "melee",
    "lifeSteal": 0.15,
    "extraHitChance": 0.5,
    "extraHitAtk": 20,
    "frameSize": 96,
    "spritePath": "assets/characters/little_spirit/",
    "effectPath": "assets/effects/little_spirit/attack.png",
    "effectFrames": 6,
    "soundPath": "assets/sounds/little_spirit/",
    "gachaRate": 10,
    "attackMethod": "공격 시 50% 확률로 2번 공격한다. 2번째 공격은 공격력 20으로 계산한다.",
    "feature": "15% 흡혈, 50% 확률 2타",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 4,
      "hit": 1,
      "dead": 2,
      "win": 4
    },
    "aiType": "rush",
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "none_little_spirit_v0.8.11_speed4_grid_removed",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 3
  },
  {
    "id": 2,
    "key": "meongdungi",
    "name": "멍둥이",
    "grade": "NORMAL",
    "hp": 180,
    "atk": 20,
    "def": 20,
    "attackSpeed": 1,
    "attackArea": 60,
    "attackRange": 2,
    "moveSpeed": 2,
    "bodyRadius": 48,
    "stopGap": 16,
    "critRate": 0.15,
    "attackType": "projectile",
    "projectilePath": "assets/projectiles/meongdungi/stone.png",
    "projectileSpeed": 520,
    "frameSize": 96,
    "spritePath": "assets/characters/meongdungi/",
    "effectPath": "assets/effects/meongdungi/attack.png",
    "effectFrames": 5,
    "gachaRate": 10,
    "attackMethod": "입에서 돌맹이가 나옴",
    "feature": "돌멩이 투사체",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "soundPath": "assets/sounds/meongdungi/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 2,
    "gridAttackRange": 2,
    "gridBattleRule": "30_columns_full_engine",
    "projectileSpeedCells": 8,
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "projectileFrames": 1,
    "projectileStartFrame": 0,
    "projectileFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2
  },
  {
    "id": 1,
    "key": "normal_man",
    "name": "걍사람",
    "grade": "NORMAL",
    "hp": 180,
    "atk": 20,
    "def": 20,
    "attackSpeed": 1,
    "attackArea": 45,
    "attackRange": 2,
    "moveSpeed": 2,
    "bodyRadius": 48,
    "stopGap": 16,
    "critRate": 0.15,
    "attackType": "melee",
    "frameSize": 96,
    "spritePath": "assets/characters/normal_man/",
    "effectPath": "assets/effects/normal_man/attack.png",
    "effectFrames": 5,
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "soundPath": "assets/sounds/normal_man/",
    "gridMovementRule": "screen_width_30_cells",
    "gachaRate": 10,
    "gridMoveSpeed": 2,
    "gridAttackRange": 2,
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2,
    "feature": "기본 근거리"
  },
  {
    "id": 13,
    "key": "slimecute",
    "name": "걍슬라임",
    "grade": "EPIC",
    "hp": 85,
    "atk": 90,
    "def": 20,
    "attackSpeed": 2,
    "attackArea": 2,
    "attackRange": 2,
    "gridAttackRange": 2,
    "moveSpeed": 3,
    "gridMoveSpeed": 3,
    "bodyRadius": 42,
    "stopGap": 14,
    "critRate": 0.15,
    "attackType": "melee",
    "paralyzeChance": 1.0,
    "paralyzeDuration": 1.0,
    "paralyzeCooldownAfter": 2.0,
    "frameSize": 96,
    "spritePath": "assets/characters/slimecute/",
    "effectPath": "assets/effects/slimecute/attack.png",
    "effectFrames": 4,
    "soundPath": "assets/sounds/slimecute/",
    "gachaRate": 10,
    "attackMethod": "공격 시 100% 확률로 상대방을 1초 마비시킨다. 마비 후 2초 동안 다시 마비되지 않는다.",
    "feature": "1초 마비, 2초 재마비 방지",
    "animations": {
      "idle": 2,
      "walk": 6,
      "attack": 6,
      "hit": 1,
      "dead": 2,
      "win": 4
    },
    "aiType": "rush",
    "gridBattleRule": "30_columns_full_engine",
    "rangeMultiplierApplied": "none_slimecute_v0.8.15_grid_removed_paralyze_cooldown",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2
  },
  {
    "id": 8,
    "key": "storm_spirit",
    "name": "폭풍정령",
    "grade": "LEGENDARY",
    "hp": 120,
    "atk": 35,
    "def": 80,
    "attackSpeed": 5,
    "attackArea": 70,
    "attackRange": 4,
    "moveSpeed": 3,
    "bodyRadius": 56,
    "stopGap": 18,
    "critRate": 0.15,
    "attackType": "projectile",
    "projectilePath": "assets/projectiles/storm_spirit/tornado.png",
    "projectileSpeed": 680,
    "projectileFrames": 6,
    "frameSize": 96,
    "spritePath": "assets/characters/storm_spirit/",
    "effectPath": "assets/effects/storm_spirit/attack.png",
    "effectFrames": 6,
    "gachaRate": 10,
    "attackMethod": "강력한 회오리를 발사",
    "feature": "회오리 발사",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "aiType": "projectile",
    "soundPath": "assets/sounds/storm_spirit/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 3,
    "gridAttackRange": 4,
    "gridBattleRule": "30_columns_full_engine",
    "projectileSpeedCells": 8,
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "projectileStartFrame": 0,
    "projectileFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2.5
  },
  {
    "id": 9,
    "key": "vampire_king",
    "name": "뱀파이어킹",
    "grade": "SUPER EPIC",
    "hp": 100,
    "atk": 35,
    "def": 50,
    "attackSpeed": 2,
    "attackArea": 90,
    "attackRange": 6,
    "moveSpeed": 3,
    "bodyRadius": 56,
    "stopGap": 18,
    "critRate": 0.15,
    "attackType": "projectile",
    "projectilePath": "assets/projectiles/vampire_king/blood_wave.png",
    "projectileSpeed": 580,
    "projectileFrames": 6,
    "lifeSteal": 0.2,
    "frameSize": 96,
    "spritePath": "assets/characters/vampire_king/",
    "effectPath": "assets/effects/vampire_king/attack.png",
    "effectFrames": 6,
    "gachaRate": 10,
    "attackMethod": "술잔에 든 진한 빨간 피를 흩뿌린다",
    "feature": "20% 흡혈",
    "animations": {
      "idle": 2,
      "walk": 4,
      "attack": 3,
      "hit": 1,
      "dead": 2
    },
    "aiType": "projectile",
    "soundPath": "assets/sounds/vampire_king/",
    "gridMovementRule": "screen_width_30_cells",
    "gridMoveSpeed": 3,
    "gridAttackRange": 6,
    "gridBattleRule": "30_columns_full_engine",
    "projectileSpeedCells": 8,
    "rangeMultiplierApplied": "x2_v0.6.1",
    "effectStartFrame": 0,
    "effectFrameWidth": 96,
    "projectileStartFrame": 0,
    "projectileFrameWidth": 96,
    "critDamageMin": 1.5,
    "critDamageMax": 2.5
  }
];
